# Generated by Django 4.0.2 on 2023-01-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_alter_category_slug_alter_post_category_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
    ]
